### PR TITLE
Enable Acknowledging Multiple ackIds at once.

### PR DESCRIPTION
**Pull request by thancock14**
Need to Enable Multiple Ack at once

### CODE REVIEW

**Comment by thancock14** [comment]
@KyleCrowley   How do you handle PR's?
Will you be able to Merge something like this in and release a new version to nuget.org?

**Comment by KyleCrowley** [comment]
Sure thing. I'll merge it in and do a NuGet push within the next few days.
I'll bump the thread/close the issue when complete.

**Comment by KyleCrowley** [comment]
@thancock14 Merged and pushed to NuGet. Give NuGet some time before attempting pull down 1.0.2. 

Thanks for the PR, btw!

**Comment by thancock14** [comment]
Thank you!

**Pull request merged**
